/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.politaktiv.map.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Layer service. Represents a row in the &quot;politaktivmaptwo_Layer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.politaktiv.map.model.impl.LayerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.politaktiv.map.model.impl.LayerImpl}.
 * </p>
 *
 * @author Paul Butenko
 * @see Layer
 * @see org.politaktiv.map.model.impl.LayerImpl
 * @see org.politaktiv.map.model.impl.LayerModelImpl
 * @generated
 */
public interface LayerModel extends BaseModel<Layer> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a layer model instance should use the {@link Layer} interface instead.
	 */

	/**
	 * Returns the primary key of this layer.
	 *
	 * @return the primary key of this layer
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this layer.
	 *
	 * @param primaryKey the primary key of this layer
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the layer ID of this layer.
	 *
	 * @return the layer ID of this layer
	 */
	public long getLayerId();

	/**
	 * Sets the layer ID of this layer.
	 *
	 * @param layerId the layer ID of this layer
	 */
	public void setLayerId(long layerId);

	/**
	 * Returns the label of this layer.
	 *
	 * @return the label of this layer
	 */
	@AutoEscape
	public String getLabel();

	/**
	 * Sets the label of this layer.
	 *
	 * @param label the label of this layer
	 */
	public void setLabel(String label);

	/**
	 * Returns the user ID of this layer.
	 *
	 * @return the user ID of this layer
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this layer.
	 *
	 * @param userId the user ID of this layer
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this layer.
	 *
	 * @return the user uuid of this layer
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this layer.
	 *
	 * @param userUuid the user uuid of this layer
	 */
	public void setUserUuid(String userUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Layer layer);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Layer> toCacheModel();

	@Override
	public Layer toEscapedModel();

	@Override
	public Layer toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}