/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.politaktiv.map.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Marker service. Represents a row in the &quot;politaktivmaptwo_Marker&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.politaktiv.map.model.impl.MarkerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.politaktiv.map.model.impl.MarkerImpl}.
 * </p>
 *
 * @author Paul Butenko
 * @see Marker
 * @see org.politaktiv.map.model.impl.MarkerImpl
 * @see org.politaktiv.map.model.impl.MarkerModelImpl
 * @generated
 */
public interface MarkerModel extends BaseModel<Marker>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a marker model instance should use the {@link Marker} interface instead.
	 */

	/**
	 * Returns the primary key of this marker.
	 *
	 * @return the primary key of this marker
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this marker.
	 *
	 * @param primaryKey the primary key of this marker
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the marker ID of this marker.
	 *
	 * @return the marker ID of this marker
	 */
	public long getMarkerId();

	/**
	 * Sets the marker ID of this marker.
	 *
	 * @param markerId the marker ID of this marker
	 */
	public void setMarkerId(long markerId);

	/**
	 * Returns the group ID of this marker.
	 *
	 * @return the group ID of this marker
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this marker.
	 *
	 * @param groupId the group ID of this marker
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this marker.
	 *
	 * @return the company ID of this marker
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this marker.
	 *
	 * @param companyId the company ID of this marker
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this marker.
	 *
	 * @return the user ID of this marker
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this marker.
	 *
	 * @param userId the user ID of this marker
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this marker.
	 *
	 * @return the user uuid of this marker
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this marker.
	 *
	 * @param userUuid the user uuid of this marker
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this marker.
	 *
	 * @return the user name of this marker
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this marker.
	 *
	 * @param userName the user name of this marker
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this marker.
	 *
	 * @return the create date of this marker
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this marker.
	 *
	 * @param createDate the create date of this marker
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this marker.
	 *
	 * @return the modified date of this marker
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this marker.
	 *
	 * @param modifiedDate the modified date of this marker
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this marker.
	 *
	 * @return the title of this marker
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this marker.
	 *
	 * @param title the title of this marker
	 */
	public void setTitle(String title);

	/**
	 * Returns the content of this marker.
	 *
	 * @return the content of this marker
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this marker.
	 *
	 * @param content the content of this marker
	 */
	public void setContent(String content);

	/**
	 * Returns the longitude of this marker.
	 *
	 * @return the longitude of this marker
	 */
	@AutoEscape
	public String getLongitude();

	/**
	 * Sets the longitude of this marker.
	 *
	 * @param longitude the longitude of this marker
	 */
	public void setLongitude(String longitude);

	/**
	 * Returns the latitude of this marker.
	 *
	 * @return the latitude of this marker
	 */
	@AutoEscape
	public String getLatitude();

	/**
	 * Sets the latitude of this marker.
	 *
	 * @param latitude the latitude of this marker
	 */
	public void setLatitude(String latitude);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Marker marker);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Marker> toCacheModel();

	@Override
	public Marker toEscapedModel();

	@Override
	public Marker toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}